language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: nvYL6G0axSgEbN5scoJh39opyMn6PQSllfnl4uVioHHvQcL4ZsL0ObZOEXxSA7LSZ9MBRX1f9BPcdC8Gfmw986T4UYmDBm3WDT/5vzkWZVEYYTIci9dyn3/kEZa/vHpFwoeTXUpWoLc7iVL4f/ZfkpZVaBt8SO59Na5J00mFUqUIhpuELf4x+r5vPU8o5NqJmONtMgotLehLazCADcRtHcLfgzC4wUsB3x9FW1R1Ux4xICPumRqFvY6rk/cxDMRkiI/wvwcwcbdBXVRnK8uT2fLNXB96ji+OnTm95/Dc7OSEly0SmePC0n2w9YQf7XmUb4WkpaTcc5A0ZevqmMzWGW3U6+I5lwmqYiHYurRDMiZmPpMVITEh3qWTuVwtKXqHuSmWbtO1mLZ0z4/+Om/mOwqy4oVlK1w5Meeg+El5NN/uXkb1HR2pZq723jlvWqgp6Mg+8iOIj/zKa6u1U6ALOSDcMzwt2DxGjBWNf/258Z5JeEwHEN5ddQoXp6VwBcWEY18RtLh9L1PTj7sIP9gEwbJjks/w8am7hvP5NDYBFW9jtXpOP1f9eD49EtaWVv6IXNYtpxWjsUYFnvJ4Lu5HEvjmJgXJyt5rd8z1JonEh91EbclVQfByks4P7+Yc9Nd9Hhhci0jEECiHixh++TF3prNypmz32AU7t8Ovm30oIRg=
node_js:
- '6'
branches:
  only:
  - master
install:
- npm install
before_script:
- npm prune
- npm run build
script:
- if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then npm run test; fi
after_success:
- if [ "$TRAVIS_EVENT_TYPE" = "push" ]; then npm run release; fi
